<?php
require_once __DIR__ . '/private/inc/bootstrap.php';
?>
<!DOCTYPE html>
<html lang="en-IN">
<head>
<?php include PRIV . '/inc/head.php'; ?>
<title>Privacy Policy — Swanya Pharmaceuticals Pvt Ltd</title>
<meta name="description" content="How Swanya Pharmaceuticals collects, uses and protects personal data on this site under India's DPDP Act 2023: cookies, analytics, forms, retention, rights.">
<link rel="canonical" href="<?= v('SITE_URL') ?>/privacy-policy">
<meta property="og:type" content="website"><meta property="og:site_name" content="Swanya Pharmaceuticals Pvt Ltd">
<meta property="og:title" content="Privacy Policy — Swanya Pharmaceuticals Pvt Ltd"><meta property="og:description" content="How Swanya Pharmaceuticals collects, uses and protects personal data on this site under India's DPDP Act 2023: cookies, analytics, forms, retention, rights.">
<meta property="og:url" content="<?= v('SITE_URL') ?>/privacy-policy"><meta property="og:image" content="<?= v('SITE_URL') ?>/assets/img/og/og-home.jpg">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="Privacy Policy — Swanya Pharmaceuticals Pvt Ltd"><meta name="twitter:image" content="<?= v('SITE_URL') ?>/assets/img/og/og-home.jpg">
<style>.legal{max-width:820px}.legal h2{scroll-margin-top:100px}.legal__meta{font-family:var(--f-mono);font-size:12.5px;color:var(--body-light);margin-bottom:28px}.toc{padding:18px 22px;border:1px solid var(--line);border-radius:var(--radius);background:var(--surface);margin-bottom:34px}.toc b{display:block;margin-bottom:8px;color:var(--ink)}.toc ol{padding-left:1.2em;list-style:decimal;font-size:14.5px;columns:2;gap:24px}.toc li+li{margin-top:4px}.toc a{color:var(--primary)}</style>
<script type="application/ld+json">{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"<?= v('SITE_URL') ?>/"},{"@type":"ListItem","position":2,"name":"Privacy Policy","item":"<?= v('SITE_URL') ?>/privacy-policy"}]}</script>
</head>
<body>
<?php include PRIV . '/inc/header.php'; ?>
<main id="main">
<section class="phero" aria-labelledby="h1">
  <div class="phero__mesh"></div>
  <div class="container">
    <nav aria-label="Breadcrumb"><ol class="breadcrumb"><li><a href="/">Home</a></li><li aria-current="page">Privacy Policy</li></ol></nav>
    <span class="eyebrow">Legal</span>
    <h1 id="h1">Privacy Policy</h1>
  </div>
</section>
<section class="section"><div class="container"><div class="legal prose">
<p class="legal__meta">Last updated: 11 September 2026 · Applies to <?= v('SITE_URL') ?></p>
<div class="toc"><b>Contents</b><ol><li><a href="#who">Who we are</a></li><li><a href="#data">Data we collect</a></li><li><a href="#purpose">Purpose &amp; legal basis</a></li><li><a href="#cookies">Cookies &amp; analytics</a></li><li><a href="#third">Third-party services</a></li><li><a href="#retention">Retention</a></li><li><a href="#rights">Your rights</a></li><li><a href="#security">Security</a></li><li><a href="#grievance">Grievance officer</a></li><li><a href="#changes">Changes</a></li></ol></div>

<h2 id="who">1. Who we are</h2>
<p>This website is operated by <strong>Swanya Pharmaceuticals Pvt Ltd</strong> ("Swanya", "we", "us"), a sterile liquid pharmaceutical manufacturer located in Baddi, Himachal Pradesh, India. For the purposes of the Digital Personal Data Protection Act, 2023 ("DPDP Act"), Swanya is the <em>Data Fiduciary</em> for personal data processed through this website.</p>

<h2 id="data">2. Data we collect</h2>
<p>We collect personal data only when you choose to provide it or when it is generated by your use of the site:</p>
<ul>
  <li><strong>Enquiry and quotation forms</strong> — name, company, work email, phone / WhatsApp number, enquiry type, product of interest and your message.</li>
  <li><strong>Career applications</strong> — name, email, phone, position applied for, experience, location, cover note and your CV file (PDF/Word).</li>
  <li><strong>Product enquiries</strong> — the same fields as the enquiry form, plus the product page you came from.</li>
  <li><strong>Technical data</strong> — IP address, browser type, device, pages visited, referring URL and approximate location, collected through server logs and analytics (see section 4).</li>
  <li><strong>WhatsApp, phone and email</strong> — if you contact us through those channels, the information you share and the metadata of the conversation.</li>
</ul>
<p>We do not knowingly collect data from children under 18, and this website is not directed at them.</p>

<h2 id="purpose">3. Purpose and legal basis</h2>
<p>We process your data for the following purposes, on the basis of your <strong>consent</strong> (given when you submit a form or accept cookies) or for <strong>legitimate uses</strong> permitted by the DPDP Act:</p>
<ul>
  <li>Responding to enquiries, preparing quotations and arranging site visits.</li>
  <li>Evaluating job applications and communicating about recruitment.</li>
  <li>Running, securing and improving the website, including preventing spam and abuse (honeypot fields, rate limiting, optional reCAPTCHA).</li>
  <li>Measuring site usage in aggregate through analytics.</li>
  <li>Complying with legal obligations, including pharmaceutical regulatory requirements.</li>
</ul>
<p>We do not sell personal data, and we do not use it for automated decision-making that produces legal effects.</p>

<h2 id="cookies">4. Cookies and analytics</h2>
<p>This site uses a small number of cookies and similar technologies:</p>
<ul>
  <li><strong>Strictly necessary</strong> — session and security cookies required for forms and rate limiting. These cannot be switched off.</li>
  <li><strong>Analytics</strong> — Google Tag Manager and Google Analytics 4 (GA4) set cookies such as <code>_ga</code> to measure visits, pages viewed and interactions such as form submissions, PDF downloads and WhatsApp/phone clicks. IP addresses are anonymised where the tool permits. <!-- TODO: confirm with client — cookie banner / consent mode implementation --></li>
</ul>
<p>You can block or delete cookies in your browser settings; the site will continue to work, but some conveniences may be unavailable.</p>

<h2 id="third">5. Third-party services</h2>
<ul>
  <li><strong>Google Analytics 4 / Google Tag Manager</strong> — usage measurement. Google may process data outside India in accordance with its own privacy policy.</li>
  <li><strong>Google Maps</strong> — the map on our Contact page loads only when you click "Load map"; at that point Google receives your IP address and browser information.</li>
  <li><strong>Google Fonts</strong> — typefaces are loaded from Google's servers, which receive your IP address.</li>
  <li><strong>WhatsApp (Meta)</strong> — if you use the WhatsApp button, your conversation is subject to WhatsApp's terms and privacy policy.</li>
  <li><strong>Email delivery</strong> — form submissions are sent to our staff via an SMTP email provider. <!-- TODO: confirm with client — name of email/hosting provider --></li>
  <li><strong>Hosting</strong> — the website and its submission records are hosted with <span class="todo">TODO: hosting provider &amp; region</span>.</li>
</ul>
<p>We share personal data with these processors only as needed to provide the service, and never for their own marketing.</p>

<h2 id="retention">6. Retention</h2>
<ul>
  <li>Enquiry and quotation data — retained for up to <strong>3 years</strong> from the last contact, or longer if a business relationship follows.</li>
  <li>Career applications and CVs — retained for <strong>12 months</strong> after the position closes, unless you ask us to delete them earlier or you are hired.</li>
  <li>Server logs — retained for up to <strong>90 days</strong> for security purposes.</li>
  <li>Analytics data — retained according to the GA4 setting in force (currently 14 months).</li>
</ul>

<h2 id="rights">7. Your rights</h2>
<p>Under the DPDP Act you have the right to:</p>
<ul>
  <li><strong>Access</strong> a summary of the personal data we hold about you and how it has been processed.</li>
  <li><strong>Correct, complete or update</strong> inaccurate or incomplete data.</li>
  <li><strong>Erase</strong> your data where it is no longer necessary for the purpose it was collected for.</li>
  <li><strong>Withdraw consent</strong> at any time, without affecting processing done before withdrawal.</li>
  <li><strong>Grievance redressal</strong> through the officer named below, and thereafter the Data Protection Board of India.</li>
  <li><strong>Nominate</strong> another individual to exercise these rights on your behalf in the event of death or incapacity.</li>
</ul>
<p>To exercise any right, email the grievance officer with "Data request" in the subject line. We respond within the time limits prescribed by law.</p>

<h2 id="security">8. Security</h2>
<p>The site is served over HTTPS. Form submissions are validated and rate-limited on the server, stored in access-controlled storage and forwarded by email only to the staff who need them. CV files are checked for type and size and stored outside the public web root. No method of transmission or storage is completely secure, so we cannot guarantee absolute security, but we review our controls regularly.</p>

<h2 id="grievance">9. Grievance officer</h2>
<p>In accordance with the DPDP Act and the Information Technology Act, 2000, the grievance officer for this website is:</p>
<p><!-- TODO: confirm with client — grievance officer name, designation, email, phone --><strong>Name:</strong> <span class="todo">TODO</span><br><strong>Designation:</strong> <span class="todo">TODO</span><br><strong>Email:</strong> <a href="mailto:<?= v('EMAIL') ?>"><?= v('EMAIL') ?></a><br><strong>Address:</strong> Swanya Pharmaceuticals Pvt Ltd, Baddi, Himachal Pradesh, India</p>

<h2 id="changes">10. Changes to this policy</h2>
<p>We may update this policy to reflect changes in law or in the services we use. The "last updated" date at the top of the page shows the current version; material changes will be highlighted on this page.</p>
</div></div></section></main>
<?php include PRIV . '/inc/footer.php'; ?>
</body>
</html>
